// Guided decision templates — pre-fill a receipt with the right questions for a
// specific kind of choice, so the blank page never feels intimidating.
export const DECISION_TEMPLATES = [
  {
    id: 'job-offer',
    emoji: '💼',
    name: 'Job offer',
    category: 'Career',
    prefill: {
      title: 'Should I take the job at …?',
      optionsConsidered: 'Accept · Decline · Negotiate first',
      mainReason: '',
      pros: 'Compensation:\nGrowth & learning:\nPeople / manager:\nLifestyle:',
      cons: 'What I’d give up:\nWhat worries me:',
      risks: 'What if the role isn’t what’s described?',
      changeMind: 'A stronger counter-offer; red flags in references',
      futureMeNote: 'Why this felt like the right move for me right now.',
    },
  },
  {
    id: 'big-purchase',
    emoji: '🛒',
    name: 'Big purchase',
    category: 'Purchases',
    prefill: {
      title: 'Should I buy …?',
      optionsConsidered: 'Buy now · Wait · Cheaper alternative',
      pros: 'How I’ll actually use it:\nWhat it improves:',
      cons: 'True total cost:\nWill I still want it in a month?',
      changeMind: 'A sale; a better option; not using it enough',
      futureMeNote: 'The honest reason behind this purchase.',
    },
  },
  {
    id: 'relationship',
    emoji: '💬',
    name: 'Relationship',
    category: 'Relationships',
    prefill: {
      title: 'A choice about my relationship with …',
      mainReason: '',
      feelings: 'What I’m actually feeling:',
      pros: 'What’s working / what I’d gain:',
      cons: 'What hurts / what I’d lose:',
      changeMind: 'What would need to change for me to feel differently',
      futureMeNote: 'What I want to remember about where I am right now.',
    },
  },
  {
    id: 'relocation',
    emoji: '✈️',
    name: 'Move / relocate',
    category: 'Personal',
    prefill: {
      title: 'Should I move to …?',
      optionsConsidered: 'Move · Stay · Try it temporarily',
      pros: 'Opportunity:\nLifestyle:\nPeople:',
      cons: 'What I leave behind:\nUnknowns:',
      risks: 'What if it doesn’t feel like home?',
      futureMeNote: 'Why I’m choosing this chapter.',
    },
  },
  {
    id: 'money',
    emoji: '💰',
    name: 'Money move',
    category: 'Money',
    prefill: {
      title: 'A financial decision: …',
      optionsConsidered: 'Option A · Option B · Do nothing',
      evidence: 'The actual numbers I know:',
      pros: 'Upside:',
      cons: 'Downside / worst case:',
      changeMind: 'New information that would change the math',
    },
  },
  {
    id: 'quit',
    emoji: '🚪',
    name: 'Quit / leave',
    category: 'Career',
    prefill: {
      title: 'Should I leave …?',
      mainReason: '',
      pros: 'Why leaving could be right:',
      cons: 'What I’d miss / risk:',
      changeMind: 'What would make me want to stay',
      futureMeNote: 'The truth about why I’m considering this.',
    },
  },
]
